package com.hunantv.media.report.entity;

import c.a.a.b.a.a.b;
import java.util.Map;

@b
/* loaded from: /home/davidjosearaujo/Documents/mc/first-year/second-semester/RE/P/re-android-reversing/deofuscation/1_apk/classes.dex */
public class CommonEntity {
    public String abt;
    public String addrty;
    public String afmt;
    public String appgn;
    public String aver;
    public String cdpf;
    public String chash;
    public String dcpf;
    public String def;
    public String devci;
    public String devmf;
    public String dnst;
    public String drmdi;
    public String drmveri;
    public String dsc;
    public String encinfo;
    public Map<String, String> exCommonFields;
    public String fhash;
    public String flowt;
    public String fstime;
    public String imp4d;
    public String iskid;
    public String isndn;
    public String logver;
    public String mf;
    public String mfosver;
    public String mod;
    public String mpx;
    public String net;
    public String p2ps;
    public String p2pt;
    public String pbox;
    public String pcdnf;
    public String pptp;
    public String prottp;
    public String psdkv;
    public String pshdrt;
    public String psuuid;
    public String pver;
    public String renvtp;
    public String s2;
    public String s4k;
    public String s4kmf;
    public String scid;
    public String sfhdamf;
    public String sfhdhmf;
    public String shdrt;
    public String snum1;
    public String sptp;
    public String srpf;
    public String srplh;
    public String srpll;
    public String sshdr;
    public String suuid;
    public String svds;
    public String sver;
    public String time;
    public String tldls;
    public String url;
    public String vfmt;
    public String vfps;
    public String vid;
    public String vsri;
    public String wadls;
    public String waev;
    public String vtp = "-1";
    public String svtp = "0";
    public String proxy = "0";
    public String retry = "0";
    public String reschg = "0";
    public String sctp = "0";
    public String ptp = "0";
    public ServiceEntity service = new ServiceEntity();
    public String plat = "n";
    public String rdtp = "";
    public String s3 = "n";
    public String has_ad = "-1";
    public String prst = "";
    public String drmt = "0";
}
